### ISSUE TITLE
I need help regarding feature extraction? 

### ISSUE THREAD

**Issue by AMEERAZAM08** [MRzzm/DINet#15]
If possible can you just help me any other way to find same feature like media pipe or dlib because I'm getting error related to fast change can't be handle 
If you can release the version for feature extraction CSV file ..
That will help me alot

**Comment by davidmartinrius** [comment]
Hi @AMEERAZAM08 
did you check this out ? https://github.com/MRzzm/DINet/issues/6

**Comment by AMEERAZAM08** [comment]
yes already i think there is some setup issue where I'm lagging i don't know ,do you have any steps for that @davidmartinrius 
@MRzzm

**Comment by davidmartinrius** [comment]
I recommend to install openface from docker. In the open face repository there are the instructions for docker. It is much easy to install and use from docker. I found a lot of problems using it from the source installation.

Are you using the one from docker or the source?

**Comment by AMEERAZAM08** [comment]
no any link related that ?

**Comment by davidmartinrius** [comment]
> no any link related that ?

Section:
Quickstart usage of OpenFace with Docker (thanks Edgar Aroutiounian and Mike McDermott)

At:

https://github.com/TadasBaltrusaitis/OpenFace/wiki#quickstart-usage-of-openface-with-docker-thanks-edgar-aroutiounian-and-mike-mcdermott

**Comment by AMEERAZAM08** [comment]
thanks let me try if there anything i will contact with you ... 
Thanks alot
