### ISSUE TITLE
DeepSpeech model: where does it come from?

### ISSUE THREAD

**Issue by elmuz** [MRzzm/DINet#16]
As the title suggests. I would like to get rid of the TF dependency and trying to convert the full model to ONNX. DeepSpeech is the first challenge. It is released as a black box and doesn't seem consistent with latest official DeepSpeech releases.

Where does it come from exactly?

**Comment by elmuz** [comment]
Ok I found it. It's actually DeepSpeech version 0.1.0 https://github.com/mozilla/DeepSpeech/releases/tag/v0.1.0

**Comment by talbenha** [comment]
hi @elmuz , thanks for sharing the information
do you have maybe pytorch implementation for this model with same weight as the tensorflow version that you can share with me?
