### ISSUE TITLE
DeepSpeech

### ISSUE THREAD

**Issue by Elsaam2y** [MRzzm/DINet#23]
Hello, 

many thanks for this amazing work. I was just wondering if there was any specific reason for using this version of DeepSpeech? 

I was thinking of retraining the model with a different audio processing like using a newer version DeepSpeech or melspectrograms for example. However I want to know if you already tried so already and if there are any objections.

Thanks

**Comment by Inferencer** [comment]
> Hello,
> 
> many thanks for this amazing work. I was just wondering if there was any specific reason for using this version of DeepSpeech?
> 
> I was thinking of retraining the model with a different audio processing like using a newer version DeepSpeech or melspectrograms for example. However I want to know if you already tried so already and if there are any objections.
> 
> Thanks

if you where thinking of re-training using a cloud service let me know, the setup is confusing on those things and would like a graph so i can see loss convergance so need some guidence

**Comment by CodeCrusader66** [comment]
> 

hello，I am trying to retrain with my downloaded HDTF dataset, but the deep speech feature of BobCoker.mp4 is different with your provided BobCoker.mp4, the Average error is 0.16, I use wandb to show my tensorboard, so you can see it easily, just click a mouse . can you help me? thank you !!

**Comment by CodeCrusader66** [comment]
![image](https://github.com/MRzzm/DINet/assets/141738368/fb39fcb6-440c-43c5-b703-e54d275e601b)
my HDTF ⬆️

![image](https://github.com/MRzzm/DINet/assets/141738368/b41f9b93-e887-4238-93ed-d98ba18f796c)
your HDTF ⬆️

**Comment by Inferencer** [comment]
their bob corker is 29fps could that be it?

also did you set this up on colab by chance? been meaning to add a tensorboard myself

**Comment by cucdengjunli** [comment]
wow！thank you! so happy to see your reply！i have used 格式工厂 change the fps to 25fps~ the result is above~

**Comment by CodeCrusader66** [comment]
wow！thank you! so happy to see your reply！i have already used 格式工厂 change the fps to 25fps~ the result is above~

the reason I set this tensorboard (wandb) is that I try to reproduce your great job and share this pipeline (maybe I can help! ), after that I will added our idea in it and try to Make some small improvements. We believe it can solve Facial blur and color distortion problems，and improve the performance on large head pose.

If you are interested, could you please take 20 minutes to communicate with us? If you don't mind, we would be honored to list you as co-author，my email is codecrusader66@foxmail.com

Topics include:
1. a little improvements to DINet
2. sync loss does not converge and oscillates
3. Considerations for handling HDTF data sets

this is our reproduction results
<img width="1363" alt="image" src="https://github.com/MRzzm/DINet/assets/141738368/f3f19400-dffc-43c2-8a02-19316839910e">

thank you! looking for your reply!

**Comment by CodeCrusader66** [comment]
I promise you that I have followed exactly the steps on your readme. 😄 but the result is not as good as yours
<img width="786" alt="image" src="https://github.com/MRzzm/DINet/assets/141738368/e7099068-7887-47bd-951b-cad9624c454a">


> their bob corker is 29fps could that be it?
> 
> also did you set this up on colab by chance? been meaning to add a tensorboard myself

**Comment by Elsaam2y** [comment]
I was thinking of retraining and I managed to retrain using wav2vec instead of deep speech. However the results sometimes are not identical to the main repository. Therefore I changed the criteria and trained another lightweight model to extract the audio features using wav2vec, then mapped these features to match the expected ones of deepspeech. I also did few more changes and did some significant optimization reducing the inference latency to up to 60%. You can try it here: 

https://github.com/Elsaam2y/DINet_optimized

**Comment by ZYBOBO** [comment]
@Elsaam2y 你好，想请教一下关于DINet语音对齐的疑问。训练阶段frame和clip阶段的数据处理不一样，但是音频都是根据源域图像帧索引得到的，也就是说语音是和源域图像对齐的；frame训练阶段对于输入的源域图像维度为(b, c, h, w)，相应的音频特征维度是(b, 29, 5)，clip阶段的源域图像维度是(5b, c, h, w)，相对应的音频特征维度是(5b, 29, 5)，但是计算同步损失的音频维度确是(b, 29, 9)，我很好奇这个deepspeech提取的音频特征是怎么和图像帧进行对齐的，为什么一张源域图像需要长度为5的语音特征进行变形？进行同步损失计算的时候为啥语音特征维度又是(b, 29, 9)?
