### ISSUE TITLE
Other technology than OpenFace?

### ISSUE THREAD

**Issue by davidmartinrius** [MRzzm/DINet#3]
Hi, 

First of all, congratulations for this project. I really like it. It is not easy to find a good project like this one. (I spent a lot of hours looking for something like this with quality, easy to use and easy to train)

Do you know another technology similar to OpenFace?  I know there are a lot of face landmark detection. But, I ask you because maybe you found a better solution than OpenFace in 2023. 

Thank you,

David Martin

**Comment by MRzzm** [comment]
Hi,

I know some commercial landmark detectors (products in SenseTime, megvii etc.) can also extract smooth landmarks from videos.  Sorry that the open-sourced detector only knows openface.

**Comment by davidmartinrius** [comment]
ok, thank you. It is just that it was not easy to install in an Ubuntu 21 and also it is a little old technology. I finally managed to use it with a Docker instance.
