### ISSUE TITLE
black square covered the face

### ISSUE THREAD

**Issue by Endgame04** [MRzzm/DINet#54]
When I run inference, there is black square covered the face. Is there any command to remove the black square part?

![image](https://github.com/MRzzm/DINet/assets/142553216/476805e4-a06f-4f2e-aaf3-fc633c80f1fa)

**Comment by Inferencer** [comment]
> When I run inference, there is black square covered the face. Is there any command to remove the black square part?
> 
> ![image](https://user-images.githubusercontent.com/142553216/261966720-476805e4-a06f-4f2e-aaf3-fc633c80f1fa.png)

try a different audio sample see if that helps, also share your inference line, and any command line outputs

**Comment by Endgame04** [comment]
@Inferencer The inference line is like this:
python inference.py --mouth_region_size=256 --source_video_path=./asserts/examples/test6.mp4 --source_openface_landmark_path=./asserts/examples/testvid.csv --driving_audio_path=./asserts/examples/driving_audio_4.wav --pretrained_clip_DINet_path=./asserts/clip_training_DINet_256mouth.pth

and the result:
![blacksquare2](https://github.com/MRzzm/DINet/assets/142553216/d3550af5-62e9-4ee3-9e59-bb2ce01d7728)

**Comment by Inferencer** [comment]
> @Inferencer The inference line is like this: python inference.py --mouth_region_size=256 --source_video_path=./asserts/examples/test6.mp4 --source_openface_landmark_path=./asserts/examples/testvid.csv --driving_audio_path=./asserts/examples/driving_audio_4.wav --pretrained_clip_DINet_path=./asserts/clip_training_DINet_256mouth.pth
> 
> and the result: ![blacksquare2](https://user-images.githubusercontent.com/142553216/261989835-d3550af5-62e9-4ee3-9e59-bb2ce01d7728.png)
[requirements.txt](https://github.com/MRzzm/DINet/files/12395590/requirements.txt)


looks good to me and as you are using the default mp4 and csv it shouldn't be an openface issue, seems to be a problem with your installation, there are a few different requirement txts floating about as the original is not great, feel free to try mine

**Comment by Endgame04** [comment]
> > @Inferencer The inference line is like this: python inference.py --mouth_region_size=256 --source_video_path=./asserts/examples/test6.mp4 --source_openface_landmark_path=./asserts/examples/testvid.csv --driving_audio_path=./asserts/examples/driving_audio_4.wav --pretrained_clip_DINet_path=./asserts/clip_training_DINet_256mouth.pth
> > and the result: ![blacksquare2](https://user-images.githubusercontent.com/142553216/261989835-d3550af5-62e9-4ee3-9e59-bb2ce01d7728.png)
> > [requirements.txt](https://github.com/MRzzm/DINet/files/12395590/requirements.txt)
> 
> looks good to me and as you are using the default mp4 and csv it shouldn't be an openface issue, seems to be a problem with your installation, there are a few different requirement txts floating about as the original is not great, feel free to try mine

Thank you for the reply @Inferencer, I checked my environment almost same with yours, the differences are I used tensorflow-gpu and protobuf 3.19.6. Here is my yml environment:
[DINetenv.txt](https://github.com/MRzzm/DINet/files/12403791/DINetenv.txt)

**Comment by Inferencer** [comment]
you can try the differences such as using cpu version etc but first i recommend grabbing a video, putting it into a video editing application & changing the frame rate to 25fps then using openface to create a new csv, my guess is as the asserts are 29fps something in the frame rate conversion is failing during inference although without your command log it's hard to tell

**Comment by Endgame04** [comment]
> 

Ok. you right, my environment caused this problem, so I made a new environment and the inference result is Ok.
![image](https://github.com/MRzzm/DINet/assets/142553216/c471d390-b7e8-4277-a7f5-c99b5ad1e23e)
