### ISSUE TITLE
None

### ISSUE THREAD

**Issue by SteveSZF** [MRzzm/DINet#58]
None

**Comment by pgyilun** [comment]
问题1：理论上可以不分子文件夹。作者巧妙地处理了可能出现的不带人脸（或者人脸不适用）的空白帧问题，training_json.json中保证子文件夹中连续的9帧一定是符合要求的。如果按题主在dataset的enumerate过程再做处理变得稍微复杂。

问题2：syncnet对中文内容判定不准，可能需要重新训练syncnet。

**Comment by SteveSZF** [comment]
> 问题1：理论上可以不分子文件夹。作者巧妙地处理了可能出现的不带人脸（或者人脸不适用）的空白帧问题，training_json.json中保证子文件夹中连续的9帧一定是符合要求的。如果按题主在dataset的enumerate过程再做处理变得稍微复杂。
> 
> 问题2：syncnet对中文内容判定不准，可能需要重新训练syncnet。

问题1：但是看了作者给的数据预处理流程，没有看到判断子文件夹中连续9帧是否符合要求的操作，只是简单切分而已。而且在训练过程中，只取了每个文件夹中的第3-7帧，是否造成第1、2、8、9帧在训练过程中被浪费了？
问题2：有三个小问题：（1）从效果的角度来看，syncnet真的有用吗？如果去掉了syncnet训练，对于效果会有多大的影响？ （2）hdtf数据集以英文为主，感觉人物说话嘴都张得比较小，pbm发音的闭嘴效果确实比较好，但中文数据集的很多发音嘴都张得比较大，pbm发音的闭嘴效果是否会被影响？ （3）发音数据的平衡问题。一般的人物说话视频中pbm发音似乎偏少？

**Comment by pgyilun** [comment]
问题1：数据预处理，https://github.com/MRzzm/DINet/blob/3b57fb0a2482213327890fbb76baeafdaa412597/data_processing.py#L99-L102

问题2：syncnet非常关键对效果影响很大。而且syncnet训练比较困难，鲁棒性一般般。

**Comment by SteveSZF** [comment]
> 问题1：数据预处理，
> 
> https://github.com/MRzzm/DINet/blob/3b57fb0a2482213327890fbb76baeafdaa412597/data_processing.py#L99-L102
> 
> 问题2：syncnet非常关键对效果影响很大。而且syncnet训练比较困难，鲁棒性一般般。

你好，请问syncnet鲁棒性一般般，是不是就是意味着我一旦有新的数据加进去，就需要重新训练syncnet呢？

**Comment by ZYBOBO** [comment]
@SteveSZF 请教一下，对于论文中用到的音频信息有些疑惑，看代码音频是和单张source图像同步对齐的，在frame阶段的数据处理中源域图像维度是(b, c, h, w)，deepspeech的维度是(b, 29, 5)，clip阶段的数据处理源域图像维度是(b*5, c, h, w)，deepspeech的维度是(b*5, 29, 5)，看起来是一张图像对应一条deepspeech特征，但是计算同步损失的时候deepspeech_full的维度是(b, 29, 9)，方便解释一下为啥吗？
