### ISSUE TITLE
OpenFace .csv not working

### ISSUE THREAD

**Issue by davidmartinrius** [MRzzm/DINet#6]
Hi,

I installed OpenFace and I tried this two commands from an Ubuntu:

./build/bin/FeatureExtraction -f video.mp4

./build/bin/FaceLandmarkVid -f video.mp4

I tried the two output csv's. In both cases I tried the next command:

python inference.py --mouth_region_size=256 --source_video_path=/home/pc/video.mp4 --source_openface_landmark_path=/home/pc/output.csv --driving_audio_path=/home/pc/audio.wav --pretrained_clip_DINet_path=./asserts/clip_training_DINet_256mouth.pth

Unfortunately, it is not working as expected. The lips are not moving.
The output video_synthetic_face.mp4 is blurry, there is no face. So, I take for granted that I am not executing the correct feature extraction, or maybe I need some parameters that I don't know how to pass.

What is the right command to extract the face landmarks to be compatible with DINet?

Thank you!

**Comment by davidmartinrius** [comment]
Well, for anyone that needs I realized I was missing some parameters that are already explained in the documentation: :rofl: 

Just do:
./build/bin/FeatureExtraction  -2Dfp -aus -tracked -f video.mp4

I don't know if there is another important parameter, but the inference with that video and the csv is working properly.

**Comment by ZYBOBO** [comment]
> Well, for anyone that needs I realized I was missing some parameters that are already explained in the documentation: 🤣
> 
> Just do: ./build/bin/FeatureExtraction -2Dfp -aus -tracked -f video.mp4
> 
> I don't know if there is another important parameter, but the inference with that video and the csv is working properly.

感谢提供的说明@davidmartinrius。
注意到asserts.zip中提供了推理用的.csv文件（比如说test1.csv）和训练示例.csv文件（比如说BobCorker_0.csv），但训练示例文件中比推理文件的内容多了AU_XX的说明，这是不是表示训练和推理用到的特征提取命令不一样？方便提供一下得到训练示例.csv文件的运行命令吗？再次表示感谢！
