### ISSUE TITLE
尝试使用HDTF数据集训练模型

### ISSUE THREAD

**Issue by 1129571** [MRzzm/DINet#63]
训练128x128的模型速度特别慢。12个小时左右才跑了一个epoch，有什么解决办法吗
![屏幕截图 2023-09-27 103154](https://github.com/MRzzm/DINet/assets/52963740/43859de6-0852-4d8f-804b-e1f6cf3a090b)

**Comment by A11enCheung** [comment]
是怎么回事呢？有没有下文？

**Comment by 1129571** [comment]
> 是怎么回事呢？有没有下文？

windows有个共享GPU内存，不要使用那个。可以搜索怎么关闭它，或者手动降低batch_size直至训练时上图曲线只在专用GPU上跑
