### ISSUE TITLE
Lips are not driven when using custom videos.

### ISSUE THREAD

**Issue by GreatWildFire** [MRzzm/DINet#68]
Lips are not driven when using custom videos. There is only a small transparent box near the eyes, but using example video is OK. It was determined that the audio was not the cause of the problem. Do you have any suggestions for this problem?Thanks

**Comment by natlamir** [comment]
Are you using OpenFace to generate the csv for the current video. I had that problem when I either didn't use OpenFace to generate the video, or when I forgot to uncheck the additional check boxes on the menu in OpenFace before generating the csv.

**Comment by GreatWildFire** [comment]
> Are you using OpenFace to generate the csv for the current video. I had that problem when I either didn't use OpenFace to generate the video, or when I forgot to uncheck the additional check boxes on the menu in OpenFace before generating the csv.

Yes, the issue was resolved when I configured openface exactly as the readme specified several Settings.Thankyou!!!!!!YYDS HAHAHA
