### ISSUE TITLE
Question about facial size change error

### ISSUE THREAD

**Issue by HenryKang1** [MRzzm/DINet#9]
I got the error about this. 'our method can not handle videos with large change of facial size!!'
However my video does not have huge change about facial size. Is it open face landmark mistakes? I debug the error and it goes to the below stage and failed the inference
elif max(radius_clip) > min(radius_clip) * 1.5:
        return False, None
       
I also checked that Openface has multiple landmark setting.
CLM CLNF CECLM
Do I have to set something among this? 
I also attahced my csv file.
[new_light_English.csv](https://github.com/MRzzm/DINet/files/11106757/new_light_English.csv)

**Comment by unscript12naveen** [comment]
This error arises due to negative value of `radius_w` variable. 

Replace line 38 in `utils/data_processing.py` with:
`radius_w = abs(landmark_data_clip[:,54, 0] - landmark_data_clip[:,48, 0]) * random_scale`

This change will resolve the issue.

**Comment by cucdengjunli** [comment]
mark

**Comment by Inferencer** [comment]
i get this when i screw up my openface settings, i selected 3d landmarks instead of 2d ones
