### ISSUE TITLE
hdtf dataset preprocess

### ISSUE THREAD

**Issue by shanzhajuan** [MRzzm/DINet#97]
Hello, according to the hdtf clips processed by [https://github.com/MRzzm/HDTF], some clips have a length of 6min, may I ask how to deal with videos of different lengths? Cut a fixed length, or divide the sentence by hand?

**Comment by Inferencer** [comment]
it will split them when you start the training automatically, what it does it split them into 9 frames so if you have a video that is 25fps and 1 minute long it will create a folder for that video and inside that folder will now be 166 folders with 9 frames in each, and it will do it for every video

**Comment by shanzhajuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我已经收到了您的邮件，会尽快处理。
